import type { Metadata } from "next";

import type { ReactNode } from "react";
import "../styles/globals.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local";

import { SmoothScroll } from "@/components";
import { TRPCReactProvider } from "@/trpc/react";

const formula = localFont({
  display: "swap",
  src: "../../public/FormulaCondensed-Bold.woff",
  variable: "--font-formula",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html
      className={`${inter.variable} ${formula.variable} antialiased`}
      lang="en"
    >
      <body>
        <TRPCReactProvider>
          <SmoothScroll>{children}</SmoothScroll>
        </TRPCReactProvider>
      </body>
    </html>
  );
};

export default RootLayout;
