import type { Metadata } from "next";
import { Geist } from "next/font/google";

import type { ReactNode } from "react";

import "../styles/globals.css";
import "katex/dist/katex.css";

import { DocsLayout } from "fumadocs-ui/layouts/docs";
import { RootProvider } from "fumadocs-ui/provider/next";

import { baseOptions } from "./layout.shared";

const GeistSans = Geist({
  variable: "--font-geist",
});

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html className={`${GeistSans.variable} antialiased`} lang="en">
      <body>
        <RootProvider>
          <DocsLayout tree={{ children: [], name: "App" }} {...baseOptions()}>
            {children}
          </DocsLayout>
        </RootProvider>
      </body>
    </html>
  );
};

export default RootLayout;
